name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./website/package-lock.json
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          cd ./website
          npm install
      - name: Build website
        run: |
          cd ./website
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com